export const skillsList = [
  // Programming Languages
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Go",
  "Swift",
  "Kotlin",
  "Rust",
  "Scala",
  
  // Frontend
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "jQuery",
  "Redux",
  "Next.js",
  "Nuxt.js",
  "Bootstrap",
  "Tailwind CSS",
  "Material UI",
  "Sass",
  "Less",
  
  // Backend
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot",
  "Laravel",
  "Ruby on Rails",
  "ASP.NET",
  "GraphQL",
  "REST API",
  
  // Databases
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Firebase",
  "SQLite",
  "Oracle",
  "Microsoft SQL Server",
  
  // DevOps & Cloud
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "CI/CD",
  "Jenkins",
  
  // Mobile
  "React Native",
  "Flutter",
  "Android Development",
  "iOS Development",
  
  // Others
  "Git",
  "Linux",
  "Agile Methodologies",
  "Test Driven Development",
  "Machine Learning",
  "Data Science"
];

export const responsibilityList = [
  "Build RESTful APIs",
  "Develop responsive web applications",
  "Implement user interfaces from designs",
  "Write clean, maintainable code",
  "Optimize application performance",
  "Debug and fix production issues",
  "Collaborate with cross-functional teams",
  "Participate in code reviews",
  "Write unit and integration tests",
  "Implement CI/CD pipelines",
  "Design database schemas",
  "Migrate legacy systems",
  "Implement authentication systems",
  "Develop mobile applications",
  "Create technical documentation",
  "Research new technologies",
  "Implement security best practices",
  "Optimize database queries",
  "Build microservices architecture",
  "Implement caching strategies",
  "Develop cloud-native applications",
  "Containerize applications",
  "Monitor application performance",
  "Implement logging systems",
  "Conduct system architecture reviews",
  "Mentor junior developers",
  "Participate in Agile ceremonies",
  "Gather and analyze requirements",
  "Implement accessibility standards",
  "Develop Progressive Web Apps",
  "Integrate third-party APIs",
  "Implement payment gateways",
  "Develop chatbots",
  "Work with AI/ML models",
  "Implement data visualization"
];

export const perksList = [
  "Certificate",
  "Letter of Recommendation",
  "Flexible Hours",
  "Remote Work Options",
  "Stipend",
  "Performance Bonus",
  "Health Insurance",
  "Mental Health Benefits",
  "Gym Membership",
  "Free Meals/Snacks",
  "Paid Time Off",
  "Parental Leave",
  "Learning Budget",
  "Conference Attendance",
  "Mentorship Program",
  "Career Growth Opportunities",
  "Stock Options",
  "Retirement Plans",
  "Transportation Allowance",
  "Work From Home Setup",
  "Company Retreats",
  "Team Building Activities",
  "Employee Recognition",
  "Pet-friendly Office",
  "On-site Childcare",
  "Tuition Reimbursement",
  "Book Reimbursement",
  "Wellness Programs",
  "Employee Discounts",
  "Hackathon Participation",
  "Open Source Contributions",
  "Patent Filing Support",
  "Relocation Assistance",
  "Language Classes",
  "Volunteering Time Off",
  "Equity Compensation"
];

export const assessmentsList = [
  "Aptitude Test",
  "Technical Interview",
  "Coding Challenge",
  "System Design Round",
  "Behavioral Interview",
  "Take-home Assignment",
  "Whiteboard Session",
  "Pair Programming",
  "Debugging Test",
  "Algorithm Challenge",
  "Data Structures Test",
  "Database Design Test",
  "API Design Assessment",
  "Frontend Implementation",
  "Backend Implementation",
  "Full-stack Project",
  "Problem Solving Test",
  "Code Review Exercise",
  "Technical Presentation",
  "Case Study Analysis",
  "Live Coding Session",
  "Architecture Design",
  "Security Assessment",
  "Performance Optimization",
  "Cloud Deployment Test",
  "DevOps Challenge",
  "Machine Learning Problem",
  "Data Analysis Task",
  "Mobile App Challenge",
  "UI/UX Evaluation",
  "Accessibility Audit",
  "Agile Methodology Quiz",
  "Git Challenge",
  "CI/CD Implementation",
  "Containerization Task"
];